### ISSUE TITLE
Do not query CSR for streaming control

### ISSUE THREAD

**Issue by bsyrowik** [intel/fpga-runtime-for-opencl#134]
Our OpenCL runtime should not query a component's CSR for the CSR version (or status, etc) in the case of components with streaming control.  If a component has streaming control and all streaming interfaces, it will not have a CSR that can be queried!  We can use the autodicsovery string to detect that a component is steaming control + streaming interfaces, or perhaps we can have system integrator make the CRA address in the autodiscovery string invalid (or perhaps both?).

**Comment by bsyrowik** [comment]
@zibaiwan @pcolberg

**Comment by bsyrowik** [comment]
See uses of `OFFSET_VERSION_ID` in `acl_kernel_if.cpp`.

**Comment by intel-jisheng1** [comment]
In the case of streaming control + agent arguments, the CSR version number should still be queried from the upper-16 bits of the CRA address 0 (as it is today), and the lower 16 bits will be padded with 0.
There will be some compiler backend work required for this, because with today's streaming the status register isn't instantiated if the control is streaming. I'll be working on the compiler backend change.

**Comment by pcolberg** [comment]
@bsyrowik @intel-jisheng1 So for a streaming control kernel, there are cases where a CSR with version is present, and cases where the CSR is absent. How would you suggest should the runtime best disambiguate between these cases? Can this be deduced from the auto-discovery string only?

**Comment by bsyrowik** [comment]
I believe the autodiscovery string should be sufficient.  The CSR will be absent iff the component has streaming control and all arguments are streaming arguments (conduits, host pipes).  This may get complicated a bit in the future when we start implementing device globals.  Perhaps we can get Artem or Abhishek to weigh in on that (I'll get back to you).  However, even if there is a CSR for device globals, it should still be safe to _not_ query the version register.

**Comment by tiwaria1** [comment]
device_globals will have a compile time constant property that will direct the compiler to implement the memory in CSR registers. It is needed to support the use-case of modifiable CSR registers - this is an upgrade from HLS.

**Comment by pcolberg** [comment]
To clarify, a streaming control kernel is indentified by the presence of the [streaming subsection in the kernel section](https://github.com/intel/fpga-runtime-for-opencl/blob/53d8136be40a0327598dd2676401dd0e2a1d04bf/src/acl_auto_configure.cpp#L676-L696). When the streaming kernel section is present, the CSR is absent and the runtime instead uses the [streaming control API to the simulator MMD](https://github.com/intel/fpga-runtime-for-opencl/issues/135) to start a kernel and query for its completion. It's probably a good idea to refer to the streaming kernel section as the `streaming control section` in the auto-discovery string parsing to make this clear.
