### ISSUE TITLE
Support streaming control in simulation

### ISSUE THREAD

**Issue by anandhv** [intel/fpga-runtime-for-opencl#135]
If the IP uses streaming control:

- instead of writing to the _start_ bit in the CRA, call a new simMMD function (name to be specified by Peter, let's call it `streaming_start` for this writeup). Provide an ID of the kernel that is being started (the type of this ID is TBD....likely it will be kernel name). streaming_start() will return a status code (pass/fail). streaming_start() will write to the corresponding streaming BFM (hostchannel BFM). If the BFM is somehow full (very unlikely), will return fail. Runtime can error out.
- when IP's `done` output asserts, it will be captured by the corresponding streaming BFM (hostchannel BFM) which will do a write to corresponding socket. At the same time, a kernel interrupt will be triggered (TBD exactly how the sim process will do this, but Bain and I have some ideas). Runtime will call a new simMMD function (Peter to pick a name, let's call 'streaming_done' for this writeup). Peter will look at how the runtime currently handles the case of multiple kernels being finished at the same time and we'll implement streaming_done() behave similarly. Perhaps the runtime does a round-robin of all kernels' done status. But basically this function will tell the runtime which kernel(s) are done, and then read/pop from the hostchannel socket.  We'll need to decide if this function should also communicate if a given kernel has multiple dones. Exact interface TBD.

**Comment by pcolberg** [comment]
@anandhv, from the kernel status interrupt handler, [acl_kernel_if_update_status()](https://github.com/intel/fpga-runtime-for-opencl/blob/b729c4e03eaa3b7887d6048d37f30adf979ab076/src/acl_kernel_if.cpp#L1286-L1519), the runtime retrieves the done status one kernel interrupt at a time. The interrupt handler loops over all accelerators for the given kernel and for each accelerator reads the CSR including the done bit.

**Comment by pcolberg** [comment]
To summarize the tasks for this issue:

 1. At the end of `acl_kernel_if_launch_kernel_on_custom_sof()`, instead of setting the `KERNEL_CSR_GO` bit in the CSR, call `streaming_start` for the given kernel (name) and accelerator (handle).

    https://github.com/intel/fpga-runtime-for-opencl/blob/b729c4e03eaa3b7887d6048d37f30adf979ab076/src/acl_kernel_if.cpp#L1257-L1260

    https://github.com/intel/fpga-runtime-for-opencl/blob/6e2fad379f4e4a7319115b282be5e4d2ccd0a4e6/include/acl_hal_mmd.h#L142-L143

 2. In `acl_kernel_if_update_status()`, instead of reading the CSR (including the done bit), call `streaming_done` to query the status of the kernel. Other signals such as stalled, unstall, profiling temporal status are unavailable.

    https://github.com/intel/fpga-runtime-for-opencl/blob/b729c4e03eaa3b7887d6048d37f30adf979ab076/src/acl_kernel_if.cpp#L1335-L1364

    https://github.com/intel/fpga-runtime-for-opencl/blob/6e2fad379f4e4a7319115b282be5e4d2ccd0a4e6/include/acl_hal_mmd.h#L144-L145

@bsyrowik @anandhv, would that satisfy the requirements?

**Comment by anandhv** [comment]
Yes I think this looks good

**Comment by pcolberg** [comment]
@anandhv In the case of multiple invocations of a single kernel having finished when invoking the kernel status interrupt handler, how shall the simulator MMD communicate the number of finished invocations? `acl_kernel_if_update_status()` currently [reads the finish counter from the CSR](https://github.com/intel/fpga-runtime-for-opencl/blob/c7af3b57be92a0a7f26ecfb3807516ee48620157/src/acl_kernel_if.cpp#L1448-L1451) and iterates over completed invocations to [mark them as done](https://github.com/intel/fpga-runtime-for-opencl/blob/c7af3b57be92a0a7f26ecfb3807516ee48620157/src/acl_kernel_if.cpp#L1457-L1458).

**Comment by anandhv** [comment]
@pcolberg A few background questions first about how things work with today's CRA. When the runtime gets an interrupt, how does the runtime determine which kernel(s) are done? How is the interrupt cleared? During the interrupt handling, what if more finishes occur, how are they captured/not lost? I realize I may need to help you answer these questions by looking at the CRA too.

I think the API you suggested seems reasonable but we may need to tweak it based on the answers to the above questions.

**Comment by pcolberg** [comment]
> When the runtime gets an interrupt, how does the runtime determine which kernel(s) are done?

For each physical device, the runtime maintains a list of kernels in `acl_kernel_if` that contains a queue of unfinished invocations for each kernel. When the runtime receives an interrupt from the MMD along with the physical device id, it iterates through the list of kernels for that device. For each kernel, it reads the kernel's `finish_counter`, which you have already described. Then it iterates over the queue of kernel invocations for the given number of finished invocations and marks each invocation as complete by removing it from the queue.

> How is the interrupt cleared?

The runtime does not clear the interrupt, as you noted this is done by the MMD. The runtime does clear the `done` bit for CSR versions < 19.1 and >= 2022.3.

> During the interrupt handling, what if more finishes occur, how are they captured/not lost?

As you noted this is also taken care of by the MMD.

**Comment by pcolberg** [comment]
After a brief discussion with @anandhv and @bsyrowik, we will not propagate potential errors from the simulator MMD to the runtime, at least for now. The runtime currently does not have a way to communicate asynchronous errors to SYCL, i.e., the user; at best the kernel interrupt handler would print a warning or abort the program. Potential error sources exist both for kernel start and done,  e.g., failing to write the BFM socket, unlikely backpressure, which will be handled internally in the simulator MMD.

The API between runtime and simulator MMD is not backwards-compatible between releases, which allows for a later revision to include error propagation if desired. In preparation, the new functions will both return `void`:
```c++
void (*aocl_mmd_simulation_streaming_kernel_start)(int handle, const std::string &kernel_name);

// Returns the non-negative number of finished invocations in `finish_count`.
void (*aocl_mmd_simulation_streaming_kernel_done)(int handle, const std::string &kernel_name, unsigned int& finish_count);
```

**Comment by sophimao** [comment]
@pcolberg Please remind me, is this issue in the previous comment the backward compatibility issue you talked about during yesterday's meeting, or is that something else?
