### ISSUE TITLE
Resolve Coverity static analysis issues

### ISSUE THREAD

**Issue by pcolberg** [intel/fpga-runtime-for-opencl#245]
The runtime project is transitioning from Klocwork to Coverity for static code analysis. This issue tracks the number of remaining Coverity issues on a semi-regular basis. The initial goal is to reduce the number of Coverity issues to zero and fail the [Coverity workflow](https://github.com/intel/fpga-runtime-for-opencl/blob/dd7c2cd1154c4dcfbef62852abb3d5fa30707bf9/.github/workflows/coverity.yml#L68) with a non-zero exit status on new issues. So far all Coverity issues could be addressed through reasonable code changes that fix potential bugs and/or improve code quality.

When updating this issue, attach a copy of the zip file from the Coverity workflow artifacts for archival, since artifacts are purged after some time.

To count issues, take the number of blank lines and divide by 2:
```
echo "scale=0; $(grep -c '^$' cov-errors.txt) / 2" | bc -l
```

**Comment by IlanTruanovsky** [comment]
> To count issues, take the number of paragraphs and divide by 2:

The `cov-analyze` command that runs in the workflow provides detailed information regarding the number of defects. 

I.e. for the first Coverity run: https://github.com/intel/fpga-runtime-for-opencl/actions/runs/3525211581/jobs/5913259883#step:9:53

Should we be using that instead?

**Comment by zibaiwan** [comment]
Thanks everyone's effort, especially @tylerzhao7684, we have 0 Coverity issue now
