### ISSUE TITLE
Implement OpenCL 3.0 clCreateImageWithProperties

### ISSUE THREAD

**Issue by sherry-yuan** [intel/fpga-runtime-for-opencl#90]
https://github.com/intel/fpga-runtime-for-opencl/blob/950f21dd079dfd55a473ba4122a4a9dca450e36f/include/CL/cl_icd.h#L154-L170

**Comment by pcolberg** [comment]
Closing due to https://github.com/intel/fpga-runtime-for-opencl/pull/57#issuecomment-1082426853.
