### ISSUE TITLE
Support program-scope host pipes

### ISSUE THREAD

**Issue by pcolberg** [intel/fpga-runtime-for-opencl#92]
Support program-scope host pipes as part of [SYCL_INTEL_data_flow_pipes](https://github.com/intel/llvm/blob/4072557b121d0fb322a5e167cc8905209f21ab3e/sycl/doc/extensions/supported/sycl_ext_intel_dataflow_pipes.asciidoc), which are statically allocated in the OpenCL program and communicated from the FPGA compiler to the FPGA runtime via the auto-discovery string.

**Comment by pcolberg** [comment]
The runtime currently implements `cl_mem` object-based host pipes:
- [clCreatePipeIntelFPGA()](https://github.com/intel/fpga-runtime-for-opencl/blob/49a70bbc59ab79a97b7e150e6344412a7e141918/src/acl_mem.cpp#L3886-L4022)
- [clReadPipeIntelFPGA()](https://github.com/intel/fpga-runtime-for-opencl/blob/49a70bbc59ab79a97b7e150e6344412a7e141918/src/acl_hostch.cpp#L239-L337)
- [clWritePipeIntelFPGA()](https://github.com/intel/fpga-runtime-for-opencl/blob/49a70bbc59ab79a97b7e150e6344412a7e141918/src/acl_hostch.cpp#L339-L449)

**Comment by zibaiwan** [comment]
Closed by #284.
